database_dir: "./database"
uploaded_dir: "./uploaded"
invisible_private_score: true

competition:
  name: "Competition"
  answer_column: "target"
  max_submissions: 100
  optimization_direction: "min"  # max or min
  metric: "mae"
  stop_final_submission_select: false